replicaCount: 1
namespace: x-test
nexusHost: x-test
profile: test

yamls:
  secretRef: x-test-secrets

securityWsValidation:
  service:
    baseUrl: x
    checkTokenEndpoint: x
    userInfoByTokenEndpoint: x
    basicAuth:
      username: x

httpClient:
  context:
    propagation:
      responseTimeout: 60s

elastic:
  apm:
    host: x
    port: x
    logLevel: INFO
    instrumentation: true
    sampleRate: 1.0
    spanMinDuration: -1ms
    metricsInterval: 10s
  metrics:
    export:
      host: x
      port: x
      username: x